export const SPREADSHEET_TEMPLATES = {
  "Contact Form": {
    title: "Contact Form",
    description: "Collect name, email, and a message from visitors.",
    headers: ["Name", "Email", "Message"],
    builderConfig: {
      theme: {
        font: "Outfit",
        mode: "dark",
        color: "#607AFB",
        radius: "lg",
      },
      components: [
        {
          id: "short-text-name",
          name: "name",
          type: "short-text",
          title: "Name",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "John Doe" },
        },
        {
          id: "email-email",
          name: "email",
          type: "email",
          title: "Email",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "john@example.com" },
        },
        {
          id: "long-text-message",
          name: "message",
          type: "long-text",
          title: "Message",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "Type your message here..." },
        },
      ],
      pages: [{ id: "page-1", title: "Page 1" }],
      active_page: "page-1",
      success_page: {
        title: "Thanks for contacting us!",
        description: "We'll get back to you shortly.",
        customContent: "<p>Our team will reach out soon.</p>",
      },
    },
  },

  "Newsletter Signup": {
    title: "Newsletter Signup",
    description: "Get subscribers for your product or blog updates.",
    headers: ["Name", "Email"],
    builderConfig: {
      theme: {
        font: "Outfit",
        mode: "dark",
        color: "#10B981",
        radius: "md",
      },
      components: [
        {
          id: "short-text-name",
          name: "name",
          type: "short-text",
          title: "Name (Optional)",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "Jane Doe" },
        },
        {
          id: "email-email",
          name: "email",
          type: "email",
          title: "Email Address",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "jane@example.com" },
        },
      ],
      pages: [{ id: "page-1", title: "Page 1" }],
      active_page: "page-1",
      success_page: {
        title: "You're subscribed!",
        description: "Thanks for joining our newsletter.",
        customContent: "<p>Expect exciting updates in your inbox!</p>",
      },
    },
  },

  "Lead Capture": {
    title: "Lead Capture",
    description: "Collect qualified leads from potential customers.",
    headers: ["Name", "Email", "Company", "Phone", "Message"],
    builderConfig: {
      theme: {
        font: "Outfit",
        mode: "dark",
        color: "#3B82F6",
        radius: "md",
      },
      components: [
        {
          id: "short-text-name",
          name: "name",
          type: "short-text",
          title: "Full Name",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "Alex Smith" },
        },
        {
          id: "email-email",
          name: "email",
          type: "email",
          title: "Email",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "alex@company.com" },
        },
        {
          id: "short-text-company",
          name: "company",
          type: "short-text",
          title: "Company",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "Your company name" },
        },
        {
          id: "phone-phone",
          name: "phone",
          type: "phone",
          title: "Phone Number",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "+11234567890" },
        },
        {
          id: "long-text-message",
          name: "message",
          type: "long-text",
          title: "How can we help?",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "Tell us about your needs..." },
        },
      ],
      pages: [{ id: "page-1", title: "Page 1" }],
      active_page: "page-1",
      success_page: {
        title: "Thanks for your interest!",
        description: "Our team will follow up with you shortly.",
        customContent: "<p>We'll be in touch soon.</p>",
      },
    },
  },

  "Job Application": {
    title: "Job Application",
    description: "Accept applications with essential details and resumes.",
    headers: ["Name", "Email", "Phone", "Age", "Message", "Resume"],
    builderConfig: {
      theme: {
        font: "Outfit",
        mode: "dark",
        color: "#EF4444",
        radius: "lg",
      },
      components: [
        {
          id: "short-text-name",
          name: "name",
          type: "short-text",
          title: "Full Name",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "Full name" },
        },
        {
          id: "email-email",
          name: "email",
          type: "email",
          title: "Email",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "you@example.com" },
        },
        {
          id: "phone-phone",
          name: "phone",
          type: "phone",
          title: "Phone Number",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "+1234567890" },
        },
        {
          id: "number-age",
          name: "age",
          type: "number",
          title: "Age",
          pageId: "page-1",
          required: true,
          properties: { min: 18, max: 99, placeholder: "Your age" },
        },
        {
          id: "long-text-message",
          name: "message",
          type: "long-text",
          title: "Why do you want to join us?",
          pageId: "page-1",
          required: true,
          properties: { placeholder: "Tell us why you're a great fit." },
        },
        {
          id: "file-resume",
          name: "resume",
          type: "file",
          title: "Upload Resume",
          pageId: "page-1",
          required: true,
          properties: {
            maxSize: 5,
            allowedTypes: ["image/*", "application/pdf"],
            numberOfFiles: 1,
          },
        },
      ],
      pages: [{ id: "page-1", title: "Page 1" }],
      active_page: "page-1",
      success_page: {
        title: "Application Submitted!",
        description: "We’ve received your application.",
        customContent: "<p>We'll contact you if you're shortlisted.</p>",
      },
    },
  },

  "Bug Report / Feedback": {
    title: "Bug Report / Feedback",
    description: "Let users submit bugs and general feedback.",
    headers: [
      "Name",
      "Email",
      "Bug Description",
      "Steps to Reproduce",
      "Screenshot URL",
      "Rating",
    ],
    builderConfig: {
      theme: {
        font: "Outfit",
        mode: "dark",
        color: "#6366F1",
        radius: "md",
      },
      components: [
        {
          id: "short-text-name",
          name: "name",
          type: "short-text",
          title: "Name (Optional)",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "Your name (optional)" },
        },
        {
          id: "email-email",
          name: "email",
          type: "email",
          title: "Email (Optional)",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "your@email.com" },
        },
        {
          id: "long-text-description",
          name: "bug_description",
          type: "long-text",
          title: "Describe the issue or feedback",
          pageId: "page-1",
          required: true,
          properties: {
            placeholder: "What went wrong or what would you like to suggest?",
          },
        },
        {
          id: "long-text-steps",
          name: "steps_to_reproduce",
          type: "long-text",
          title: "Steps to Reproduce (Optional)",
          pageId: "page-1",
          required: false,
          properties: {
            placeholder: "1. Go to...\n2. Click on...\n3. See the issue...",
          },
        },
        {
          id: "url-screenshot",
          name: "screenshot_url",
          type: "url",
          title: "Screenshot / Recording URL (Optional)",
          pageId: "page-1",
          required: false,
          properties: { placeholder: "https://example.com/screenshot" },
        },
        {
          id: "rating-rating",
          name: "rating",
          type: "rating",
          title: "Rate your experience",
          pageId: "page-1",
          required: false,
          properties: { maxRating: 5 },
        },
      ],
      pages: [{ id: "page-1", title: "Page 1" }],
      active_page: "page-1",
      success_page: {
        title: "Feedback Received!",
        description: "Thanks for helping us improve.",
        customContent: "<p>We appreciate your input.</p>",
      },
    },
  },
};
