import FormPreview from "@/components/form-builder/FormPreview";
import { getForm } from "@/lib/form";
import { FileWarning } from "lucide-react";
import { Metadata, ResolvingMetadata } from "next";
import { notFound } from "next/navigation";

interface FormPageProps {
  params: Promise<{
    formId: string;
  }>;
}

export default async function FormPage({ params }: FormPageProps) {
  const data = await getForm((await params).formId);

  if (!data?.id) {
    return notFound();
  }

  if (data.builder_config === null) {
    return (
      <div className="flex flex-col items-center justify-center h-[70vh] text-center px-4">
        <FileWarning className="w-12 h-12 mb-4" />
        <h1 className="text-2xl font-semibold mb-2 text-yellow-500">
          This form is empty
        </h1>
        <p className="max-w-md text-muted-foreground">
          The form creator hasn’t added any fields yet. Please check back later
          or contact the form owner if this is unexpected.
        </p>
      </div>
    );
  }

  if (!data.is_active)
    return (
      <div className="flex flex-col items-center justify-center h-[70vh] text-center px-4">
        <FileWarning className="w-12 h-12 mb-4 text-yellow-500" />
        <h1 className="text-2xl font-semibold mb-2">
          This form is no longer accepting responses
        </h1>
        <p className="max-w-md text-muted-foreground">
          This form is no longer accepting responses. If you believe this is an
          error, please contact the form owner.
        </p>
      </div>
    );

  const theme = data.builder_config.theme;

  return (
    <FormPreview
      formId={data.id}
      redirectUrl={data.redirect_url}
      formData={{
        id: data.builder_config.id,
        components: data.builder_config.components,
        theme: theme,
        pages: data.builder_config.pages,
        title: data.title,
        activePage: data.builder_config.active_page,
        successPage: data.builder_config.success_page,
      }}
    />
  );
}

export async function generateMetadata(
  { params }: FormPageProps,
  parent: ResolvingMetadata,
): Promise<Metadata> {
  const [{ formId }, data] = await Promise.all([params, getForm((await params).formId)]);

  const title = data?.title || "This form is generated by heysheet!";
  const description =
    "Fill out this form powered by heysheet. Create and share forms easily.";
  const url = `${process.env.NEXT_PUBLIC_APP_URL}/f/${formId}`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
    alternates: {
      canonical: url,
    },
  };
}
