import FormPreview from "@/components/form-builder/FormPreview";
import { getForm } from "@/lib/form";
import { SPREADSHEET_TEMPLATES } from "@/lib/spreadsheet-templates";
import { generateTheme } from "@/lib/theme";
import { FileWarning, PlusCircle } from "lucide-react";
import { Metadata, ResolvingMetadata } from "next";
import { notFound } from "next/navigation";

interface FormPageProps {
  params: Promise<{
    formId: string;
  }>;
}

export default async function FormPage({ params }: FormPageProps) {
  const { formId } = await params;
  const data = await getForm(formId);
  console.log("data", data);

  if (!data?.id) {
    return notFound();
  }

  if (data.builder_config === null) {
    return (
      <div className="flex flex-col items-center justify-center h-[70vh] text-center px-4">
        <FileWarning className="w-12 h-12 mb-4" />
        <h1 className="text-2xl font-semibold mb-2">This form is empty</h1>
        <p className="max-w-md text-muted-foreground">
          The form creator hasn’t added any fields yet. Please check back later
          or contact the form owner if this is unexpected.
        </p>
      </div>
    );
  }
  const theme = data.builder_config.theme;

  return (
    <FormPreview
      formId={data.id}
      redirectUrl={data.redirect_url}
      formData={{
        id: data.builder_config.id,
        components: data.builder_config.components,
        theme: generateTheme(theme.color, theme.font, theme.radius, theme.mode),
        pages: data.builder_config.pages,
        title: data.title,
        activePage: data.builder_config.active_page,
        successPage: data.builder_config.success_page,
      }}
    />
  );
}

export async function generateMetadata(
  { params }: FormPageProps,
  parent: ResolvingMetadata,
): Promise<Metadata> {
  const { formId } = await params;
  const data = await getForm(formId);
  return {
    title: data?.title || "This form is generated by heysheet!",
  };
}
